# ---
# Welcome to LYDDE Group Jekyll!
# Version : 1.0.0
# ---
# This site is a bootstrap 5.3 theme for Jekyll engine
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

#
# Build settings
#
theme: jekyll-theme-lydde

# 
# Site settings
# 
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#
title: YAKA Games Studio
description: We are a young indie game studio developing multiplatform IA empowered games and augmented reality experiences.
timezone: Europe/Paris
permalink: /:title
tagline: Game developer unleashed 
logo: "/assets/logo.png"
favicon: "assets/icons/favicon.ico"
language: en
locale: en_US

#
# Collections
#
collections:
  categories:
    output: true
  pages:
    output: true

#
# Defaults values
#
defaults:
# all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/images/post.jpeg
      author: koubyak
  # all categories
  - scope:
      path: ""
      type: categories
    values:
      layout: page
      image: /assets/images/page.jpeg
  # all pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: /assets/images/page.jpeg

#
# Files excluded
#
exclude:
  - readme.md

#
# Plugins used
#
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-feed  
  - jekyll-mentions
  - jekyll-redirect-from

#
# Plugin settings
#
relative_links:
  collections: true